import type { EpisodeManifest } from '../../core/types';

export const episode02: EpisodeManifest = {
  id: 'episode_02',
  title: '에피소드 02: 증기 광장의 신호',
  startSceneId: 'steam_square',
  scenes: [
    {
      id: 'steam_square',
      title: '증기 광장',
      description: '도시 내부 첫 지역. 방송탑으로 가기 위해 부품과 신호 장치를 점검한다.',
      background: 'assets/backgrounds/steam_square.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'pickup_gear',
          label: '작은 기어 줍기',
          x: 100,
          y: 360,
          w: 150,
          h: 100,
          action: { type: 'pickup', itemId: 'small_gear' },
        },
        {
          id: 'pickup_oil_can',
          label: '오일 캔 줍기',
          x: 280,
          y: 350,
          w: 150,
          h: 110,
          action: { type: 'pickup', itemId: 'oil_can' },
        },
        {
          id: 'open_signal_sequence',
          label: '신호 패널',
          x: 480,
          y: 200,
          w: 180,
          h: 170,
          action: { type: 'open_puzzle', puzzleId: 'p2_signal_sequence' },
        },
        {
          id: 'to_train_hub',
          label: '열차 제어실로',
          x: 810,
          y: 150,
          w: 120,
          h: 300,
          action: { type: 'goto', sceneId: 'train_hub' },
          requiredFlag: 'signal_panel_online',
          blockedText: '신호 패널이 비활성 상태다.',
        },
      ],
    },
    {
      id: 'train_hub',
      title: '열차 제어실',
      description: '노선 락을 풀면 방송탑 작업실로 들어갈 수 있다.',
      background: 'assets/backgrounds/train_hub.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'back_to_square',
          label: '광장으로 돌아가기',
          x: 20,
          y: 180,
          w: 120,
          h: 280,
          action: { type: 'goto', sceneId: 'steam_square' },
        },
        {
          id: 'open_route_lock',
          label: '노선 잠금 장치',
          x: 430,
          y: 190,
          w: 220,
          h: 180,
          action: { type: 'open_puzzle', puzzleId: 'p2_route_pattern' },
        },
        {
          id: 'to_radio_lab',
          label: '방송탑 작업실',
          x: 810,
          y: 150,
          w: 120,
          h: 300,
          action: { type: 'goto', sceneId: 'radio_lab' },
          requiredFlag: 'route_lock_released',
          blockedText: '노선 잠금 장치가 아직 닫혀 있다.',
        },
      ],
    },
    {
      id: 'radio_lab',
      title: '방송탑 작업실',
      description: '기어와 오일을 조합하고, 안테나 스위치를 기동해 외곽 옥상으로 이동한다.',
      background: 'assets/backgrounds/radio_lab.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'back_to_hub',
          label: '제어실로 돌아가기',
          x: 20,
          y: 170,
          w: 120,
          h: 280,
          action: { type: 'goto', sceneId: 'train_hub' },
        },
        {
          id: 'open_core_combine',
          label: '정비 테이블',
          x: 220,
          y: 280,
          w: 220,
          h: 140,
          action: { type: 'open_puzzle', puzzleId: 'p2_combine_rotor' },
        },
        {
          id: 'open_tower_switch',
          label: '안테나 스위치',
          x: 530,
          y: 210,
          w: 210,
          h: 170,
          action: { type: 'open_puzzle', puzzleId: 'p2_timed_antenna' },
          requiredItemId: 'lubricated_rotor',
          blockedText: '윤활 로터가 필요하다.',
        },
        {
          id: 'to_rooftop',
          label: '외곽 옥상으로',
          x: 820,
          y: 140,
          w: 120,
          h: 310,
          action: { type: 'goto', sceneId: 'outer_rooftop' },
          requiredFlag: 'antenna_online',
          blockedText: '안테나 전원이 아직 올라오지 않았다.',
        },
      ],
    },
    {
      id: 'outer_rooftop',
      title: '외곽 옥상',
      description: '마지막 보안 논리를 해제하고 로터를 삽입하면 2화가 완료된다.',
      background: 'assets/backgrounds/outer_rooftop.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'back_to_lab',
          label: '작업실로 돌아가기',
          x: 20,
          y: 170,
          w: 120,
          h: 280,
          action: { type: 'goto', sceneId: 'radio_lab' },
        },
        {
          id: 'open_logic_console',
          label: '보안 콘솔',
          x: 330,
          y: 220,
          w: 220,
          h: 170,
          action: { type: 'open_puzzle', puzzleId: 'p2_logic_console' },
        },
        {
          id: 'use_rotor',
          label: '신호 증폭기 슬롯',
          x: 700,
          y: 190,
          w: 200,
          h: 230,
          action: { type: 'use_item', requiredItemId: 'lubricated_rotor', successFlag: 'game_complete' },
          requiredFlag: 'console_cracked',
          blockedText: '먼저 콘솔 보안을 해제해야 한다.',
        },
      ],
    },
  ],
  puzzles: [
    {
      id: 'p2_signal_sequence',
      type: 'sequence',
      title: '신호 패널 순서',
      prompt: '도시 표식 순서를 맞춰 신호 회선을 연다.',
      config: {
        symbols: ['N', 'E', 'S', 'W'],
        correctSequence: ['W', 'N', 'E', 'S'],
      },
      successSetFlags: ['signal_panel_online'],
      hints: [
        '힌트 1: 서쪽 표식부터 시작한다.',
        '힌트 2: 두 번째는 북쪽 표식이다.',
        '힌트 3: 정답 = W -> N -> E -> S',
      ],
    },
    {
      id: 'p2_route_pattern',
      type: 'pattern_lock',
      title: '노선 락 패턴',
      prompt: '노선 노드를 올바른 순서로 선택하라.',
      config: {
        symbols: ['1', '2', '3', '4'],
        correctSequence: ['3', '1', '4', '2'],
      },
      successSetFlags: ['route_lock_released'],
      hints: [
        '힌트 1: 세 번째 노드가 시작점이다.',
        '힌트 2: 마지막은 2번 노드다.',
        '힌트 3: 정답 = 3 -> 1 -> 4 -> 2',
      ],
    },
    {
      id: 'p2_combine_rotor',
      type: 'inventory_combine',
      title: '윤활 로터 조립',
      prompt: '회전 부품과 윤활 재료를 조합하라.',
      config: {
        requiredItems: ['small_gear', 'oil_can'],
        resultItemId: 'lubricated_rotor',
      },
      successSetFlags: ['rotor_ready'],
      hints: [
        '힌트 1: 기계 부품 2개를 함께 사용한다.',
        '힌트 2: 마찰을 줄일 수 있는 재료가 필요하다.',
        '힌트 3: 정답 = small_gear + oil_can',
      ],
    },
    {
      id: 'p2_timed_antenna',
      type: 'timed_switch',
      title: '안테나 기동',
      prompt: '4초 안에 스위치를 6번 눌러라.',
      config: {
        targetClicks: 6,
        windowMs: 4000,
      },
      successSetFlags: ['antenna_online'],
      hints: [
        '힌트 1: 타이머 시작 후 연속 입력이 필요하다.',
        '힌트 2: 4초 제한 안에 횟수를 채워야 한다.',
        '힌트 3: 최소 6회 클릭',
      ],
    },
    {
      id: 'p2_logic_console',
      type: 'logic_grid',
      title: '콘솔 로직 해독',
      prompt: '합이 12이고 홀수가 1개인 조합을 고르라.',
      config: {
        options: ['4-4-4', '3-4-5', '2-4-6', '1-5-6'],
        correctIndex: 2,
      },
      successSetFlags: ['console_cracked'],
      hints: [
        '힌트 1: 합 12를 먼저 체크하라.',
        '힌트 2: 홀수는 정확히 1개다.',
        '힌트 3: 정답은 2-4-6',
      ],
    },
  ],
};
