import type { EpisodeManifest } from '../../core/types';

export const episode01: EpisodeManifest = {
  id: 'episode_01',
  title: '에피소드 01: 녹슨 도시의 전원',
  startSceneId: 'scrap_yard',
  scenes: [
    {
      id: 'scrap_yard',
      title: '고철 더미 광장',
      description: '버려진 로봇 부품 더미 속에서 시작한다. 전력을 살리면 배수로로 이동할 수 있다.',
      background: 'assets/backgrounds/scrap_yard.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'pickup_wire',
          label: '전선 줍기',
          x: 90,
          y: 380,
          w: 140,
          h: 90,
          action: { type: 'pickup', itemId: 'wire' },
          hintKey: 'wire_pile',
        },
        {
          id: 'pickup_battery',
          label: '배터리 줍기',
          x: 250,
          y: 360,
          w: 140,
          h: 100,
          action: { type: 'pickup', itemId: 'battery' },
          hintKey: 'battery_pile',
        },
        {
          id: 'open_sequence_panel',
          label: '전원 패널',
          x: 430,
          y: 210,
          w: 190,
          h: 150,
          action: { type: 'open_puzzle', puzzleId: 'p_seq_power' },
          hintKey: 'power_panel',
        },
        {
          id: 'to_sewer',
          label: '배수로 입구',
          x: 790,
          y: 150,
          w: 140,
          h: 310,
          action: { type: 'goto', sceneId: 'sewer_gate' },
          requiredFlag: 'power_restored',
          blockedText: '배수로 입구가 잠겨 있다. 먼저 전원을 복구하자.',
          hintKey: 'sewer_door',
        },
      ],
    },
    {
      id: 'sewer_gate',
      title: '배수로 제어실',
      description: '밸브 잠금 패턴을 해제하면 시계탑으로 통하는 통로가 열린다.',
      background: 'assets/backgrounds/sewer_gate.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'back_to_yard',
          label: '광장으로 돌아가기',
          x: 20,
          y: 180,
          w: 120,
          h: 260,
          action: { type: 'goto', sceneId: 'scrap_yard' },
        },
        {
          id: 'open_pattern_lock',
          label: '밸브 잠금 장치',
          x: 420,
          y: 190,
          w: 220,
          h: 170,
          action: { type: 'open_puzzle', puzzleId: 'p_pattern_valve' },
        },
        {
          id: 'to_tower',
          label: '시계탑 통로',
          x: 810,
          y: 170,
          w: 120,
          h: 280,
          action: { type: 'goto', sceneId: 'clock_tower' },
          requiredFlag: 'sewer_gate_open',
          blockedText: '밸브 잠금이 해제되지 않았다.',
        },
      ],
    },
    {
      id: 'clock_tower',
      title: '시계탑 작업실',
      description: '수리 조합과 타이밍 스위치를 해결하면 도시 문 앞까지 갈 수 있다.',
      background: 'assets/backgrounds/clock_tower.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'back_to_sewer',
          label: '배수로로 돌아가기',
          x: 20,
          y: 160,
          w: 120,
          h: 300,
          action: { type: 'goto', sceneId: 'sewer_gate' },
        },
        {
          id: 'open_combine',
          label: '수리 작업대',
          x: 220,
          y: 280,
          w: 220,
          h: 150,
          action: { type: 'open_puzzle', puzzleId: 'p_combine_core' },
        },
        {
          id: 'open_timed_switch',
          label: '발전기 스위치',
          x: 520,
          y: 200,
          w: 210,
          h: 180,
          action: { type: 'open_puzzle', puzzleId: 'p_timed_generator' },
          requiredItemId: 'power_core',
          blockedText: '전력 코어가 필요하다. 작업대에서 먼저 조립하자.',
        },
        {
          id: 'to_city_gate',
          label: '도시 외곽 문',
          x: 820,
          y: 130,
          w: 120,
          h: 320,
          action: { type: 'goto', sceneId: 'city_gate' },
          requiredFlag: 'tower_power_online',
          blockedText: '시계탑 전력 라인이 아직 비활성 상태다.',
        },
      ],
    },
    {
      id: 'city_gate',
      title: '도시 외곽 게이트',
      description: '보안 논리 잠금을 풀고 전력 코어를 삽입하면 첫 에피소드가 종료된다.',
      background: 'assets/backgrounds/city_gate.svg',
      ambientSfx: 'assets/sfx/ambient_loop.wav',
      hotspots: [
        {
          id: 'back_to_tower',
          label: '시계탑으로 돌아가기',
          x: 20,
          y: 170,
          w: 120,
          h: 280,
          action: { type: 'goto', sceneId: 'clock_tower' },
        },
        {
          id: 'open_logic_grid',
          label: '보안 콘솔',
          x: 350,
          y: 220,
          w: 220,
          h: 170,
          action: { type: 'open_puzzle', puzzleId: 'p_logic_code' },
        },
        {
          id: 'use_core_on_gate',
          label: '게이트 코어 슬롯',
          x: 700,
          y: 180,
          w: 200,
          h: 240,
          action: { type: 'use_item', requiredItemId: 'power_core', successFlag: 'game_complete' },
          requiredFlag: 'city_code_cracked',
          blockedText: '먼저 보안 코드를 해독해야 한다.',
        },
      ],
    },
  ],
  puzzles: [
    {
      id: 'p_seq_power',
      type: 'sequence',
      title: '전원 라우팅 순서',
      prompt: '패널을 올바른 순서로 눌러 전류를 연결하라.',
      config: {
        symbols: ['A', 'B', 'C', 'D'],
        correctSequence: ['B', 'D', 'A', 'C'],
      },
      successSetFlags: ['power_restored'],
      hints: [
        '힌트 1: 가장 낡은 회로(B)부터 시작한다.',
        '힌트 2: 시작 다음은 오른쪽 아래 노드다.',
        '힌트 3: 정답 순서 = B -> D -> A -> C',
      ],
    },
    {
      id: 'p_pattern_valve',
      type: 'pattern_lock',
      title: '밸브 패턴 잠금',
      prompt: '밸브 손잡이를 지정된 패턴대로 맞춰라.',
      config: {
        symbols: ['△', '○', '□', '◇'],
        correctSequence: ['◇', '○', '△', '□'],
      },
      successSetFlags: ['sewer_gate_open'],
      hints: [
        '힌트 1: 가장 뾰족한 도형이 시작점이다.',
        '힌트 2: 두 번째는 원형이다.',
        '힌트 3: 정답 순서 = ◇ -> ○ -> △ -> □',
      ],
    },
    {
      id: 'p_combine_core',
      type: 'inventory_combine',
      title: '전력 코어 조립',
      prompt: '작업대에서 맞는 부품 2개를 조합하라.',
      config: {
        requiredItems: ['wire', 'battery'],
        resultItemId: 'power_core',
      },
      successSetFlags: ['core_assembled'],
      hints: [
        '힌트 1: 고철 더미에서 얻은 2개 부품이 핵심이다.',
        '힌트 2: 전류를 전달할 것 + 저장할 것을 조합하라.',
        '힌트 3: 정답 조합 = wire + battery',
      ],
    },
    {
      id: 'p_timed_generator',
      type: 'timed_switch',
      title: '발전기 기동',
      prompt: '3초 안에 스위치를 5회 눌러 발전기를 가동하라.',
      config: {
        targetClicks: 5,
        windowMs: 3000,
      },
      successSetFlags: ['tower_power_online'],
      hints: [
        '힌트 1: 시작 후 빠르게 연타해야 한다.',
        '힌트 2: 스위치 누름 횟수는 화면 하단에서 확인할 수 있다.',
        '힌트 3: 3초 제한, 최소 5회 클릭이 필요하다.',
      ],
    },
    {
      id: 'p_logic_code',
      type: 'logic_grid',
      title: '보안 코드 추론',
      prompt: '단서: 코드 숫자 합은 10이며 짝수는 2개다. 올바른 조합을 고르라.',
      config: {
        options: ['2-3-5', '1-4-5', '2-4-4', '3-3-4'],
        correctIndex: 2,
      },
      successSetFlags: ['city_code_cracked'],
      hints: [
        '힌트 1: 합이 10인지 먼저 확인하라.',
        '힌트 2: 짝수 숫자가 정확히 2개여야 한다.',
        '힌트 3: 정답은 2-4-4',
      ],
    },
  ],
};
